apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
configMapGenerator:
  - name: public-home-content
    files:
      - index.html
generatorOptions:
  disableNameSuffixHash: true
