apiVersion: v1
kind: Namespace
metadata:
  name: app-adguard-home
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/part-of: public-cluster
    app.kubernetes.io/managed-by: argocd
    core.sedware.net/owner: platform
    core.sedware.net/purpose: application
    core.sedware.net/environment: dev
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.36
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: v1.36
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: v1.36
---
apiVersion: v1
kind: LimitRange
metadata: {name: defaults, namespace: app-adguard-home}
spec:
  limits:
  - type: Container
    defaultRequest: {cpu: 25m, memory: 64Mi}
---
apiVersion: v1
kind: ResourceQuota
metadata: {name: quota, namespace: app-adguard-home}
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 512Mi
    requests.storage: 10Gi
    persistentvolumeclaims: "2"
    pods: "4"
