apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gitlab-runner-amd64
  namespace: app-gitlab-runner
  annotations: {argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true}
spec:
  targetRef: {apiVersion: apps/v1, kind: Deployment, name: gitlab-runner-amd64}
  updatePolicy: {updateMode: "Off"}
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: [cpu, memory]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gitlab-runner-arm64
  namespace: app-gitlab-runner
  annotations: {argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true}
spec:
  targetRef: {apiVersion: apps/v1, kind: Deployment, name: gitlab-runner-arm64}
  updatePolicy: {updateMode: "Off"}
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: [cpu, memory]
      controlledValues: RequestsOnly
